### ISSUE TITLE
cannot connect to the server

### ISSUE THREAD

**Issue by xjunko** [light-ripple/Light-Ripple-Windows#9]
i did everything like the instructions say, the website is accesible and it works kinda okay (cant register, login). the only thing that doesnt work is when i tried to login in osu!. i created two account with different hashed md5 password and still doesnt work

**Comment by loannaflip** [comment]
@FireRedz can't surely say atm why it did not worked for you. You can join our discussion server here: https://discord.gg/bA8pDFX to help investigate or You can try kanaze chan's <https://github.com/Kanaze-chan/readme> one (which is updated)
